// client/src/modules/layout/SearchBar.tsx
import { SearchIcon } from "lucide-react";
import { useState, useEffect } from "react";
import type { FunctionComponent } from "react";
import { useSearchParams } from "react-router";

export const SearchBar: FunctionComponent = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const query = searchParams.get("q") ?? "";

  const [inputValue, setInputValue] = useState(query);

  useEffect(() => {
    setInputValue(query);
  }, [query]);

  useEffect(() => {
    const handler = setTimeout(() => {
      if (inputValue !== query) {
        setSearchParams(
          (prev) => {
            if (inputValue) {
              prev.set("q", inputValue);
            } else {
              prev.delete("q");
            }
            return prev;
          },
          { replace: true },
        );
      }
    }, 500);

    return () => clearTimeout(handler);
  }, [inputValue, query, setSearchParams]);

  return (
    <section className="px-4 pt-4 container-lg">
      <label className="input w-full">
        <SearchIcon className="h-[1em] opacity-50" />
        <input
          type="search"
          className="grow"
          autoComplete="off"
          placeholder="Search"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
        />
      </label>
    </section>
  );
};

// web/src/core/components/SearchBar.svelte
<script lang="ts">
  import { search } from '$nanostores/search'

  import type { Search } from '$nanostores/@types/Search'

  export let section: keyof Search
  let timer: NodeJS.Timeout

  const debounce = (value: string) => {
    clearTimeout(timer)
    timer = setTimeout(() => {
      console.log('value: ', value)
      search.setKey(section, {
        ...search.get()[section],
        query: value,
      })
    }, 500)
  }
</script>

<section class="px-4 pt-4 container-lg">
  <label class="input w-full">
    <svg class="h-[1em] opacity-50" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g stroke-linejoin="round" stroke-linecap="round" stroke-width="2.5" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="8"></circle><path d="m21 21-4.3-4.3"></path></g></svg>
    <input
      type="search"
      class="grow"
      autocomplete="off"
      placeholder="Keywords or 6-digit code"
      value={$search[section].query}
      on:input={({ target }) => {
      // @ts-ignore
      return debounce(target?.value ?? '')
    }}
    />
  </label>
  <slot />
</section>
