// apps/web-next/src/modules/main/components/listing.tsx
import React from 'react'

import { Listing } from '../../../core/components/listing'
import { Pagination } from '../../../core/components/pagination'
import { useMainNavigation } from '../services/useMainNavigation'

interface IProps {
  page: number
}

export const MainListing: React.FC<IProps> = props => {
  const { page } = props

  const { data, isLoading, isError } = useMainNavigation(page)
  // const res = useMainNavigation(page)

  return (
    <div className="p-2 sm:p-4">
      {isError ? (
        <div>Fail</div>
      ) : isLoading ? (
        <div>Load</div>
      ) : (
        <React.Fragment>
          <div className="flex justify-center pt-4">
            <nav className="z-0">
              <Pagination max={data.maxPage} current={page} prefix="/" />
            </nav>
          </div>
          <div className="py-4">
            <Listing {...{ galleries: data.galleries }} />
          </div>
          <div className="flex justify-center pb-4">
            <nav className="z-0">
              <Pagination max={data.maxPage} current={page} prefix="/" />
            </nav>
          </div>
        </React.Fragment>
      )}
    </div>
  )
}

// web/src/modules/listing/components/Listing.svelte
<script lang="ts">
  import Pagination from '$core/components/Pagination.svelte'
  import Poster from '$core/components/Poster.svelte'

  import { search } from '$nanostores/search'
  import { settings } from '$nanostores/settings'
  import { api } from '$trpc/client'

  export let section: 'main' | 'listing' | 'tag'
  export let page: number
  export let tagKey: string = ''

  const prefix =
    section === 'listing'
      ? '/listing/'
      : section === 'tag'
        ? `/tag/${tagKey}/`
        : '/'

  $: listing = api.hentai.search.query({
    mode: section,
    query: section === 'tag' ? tagKey : $search[section].query,
    excludeTags: $settings.filteredTags ?? [],
    page,
  })
</script>

{#if $listing.isLoading}
  <div class="flex flex-col items-center p-32">
    <progress class="progress w-56"></progress>
    <p class="pt-2 text-sm text-base-content">Loading...</p>
  </div>
{:else if $listing.isSuccess}
  {@const { items, maxPage } = $listing.data}

  <section class="flex justify-center py-6">
    <Pagination max={maxPage} current={page} {prefix} />
  </section>

  <section class="gallery-grid">
    {#each items as hentai}
      <a href={`/g/${hentai.id}`}>
        <Poster {hentai} />
      </a>
    {/each}
  </section>

  <section class="flex justify-center py-6">
    <Pagination max={maxPage} current={page} {prefix} />
  </section>
{:else}
  <p>Failed</p>
{/if}
