// client/src/modules/reader/Favorite.tsx
import { MinusIcon, PlusIcon } from "lucide-react";
import { useCallback, type FunctionComponent } from "react";
import { collectionsAtom, useCollectionsAtom } from "modules/atoms/collectionsAtom";
import type { Gallery } from "@riffyh/commons";

interface Props {
  gallery: Gallery;
}

export const Favorite: FunctionComponent<Props> = ({ gallery }) => {
  const collections = useCollectionsAtom();

  const isFavorite = collections.find(
    (collection) => collection.id === gallery.id && collection.key === gallery.key,
  );

  const handleToggleFavorite = useCallback(() => {
    // if exist then remove hentai from collection, otherwise add hentai to collection
    if (isFavorite) {
      collectionsAtom.set(collections.filter((o) => o.id !== gallery.id));
    } else {
      collectionsAtom.set([
        {
          id: gallery.id,
          key: gallery.key,
          title: gallery.title,
          cover: gallery.cover,
          tags: gallery.tags,
        },
        ...collections,
      ]);
    }
  }, [isFavorite, collections, collectionsAtom]);

  return (
    <button className="btn btn-square btn-secondary" onClick={handleToggleFavorite}>
      {isFavorite ? <MinusIcon className="w-8" /> : <PlusIcon className="w-7" />}
    </button>
  );
};

// src/modules/reader/Favorite.svelte
<script lang="ts">
  import PlusIcon from '$icons/plus.svelte'
  import MinusIcon from '$icons/minus.svelte'

  import { collection } from '$nanostores/collection'

  import type { Hentai } from '$core/@types/Hentai'

  export let hentai: Hentai

  $: isFavorited =
    $collection.find(o => Number(o.id) === Number(hentai.id)) !== undefined

  const onToggleCollection = () => {
    // if exist then remove hentai from collection, otherwise add hentai to collection
    if (isFavorited) {
      collection.set(
        collection.get().filter(o => Number(o.id) !== Number(hentai.id))
      )
    } else {
      collection.set([
        {
          id: hentai.id,
          internal: false,
          data: { ...hentai, images: { ...hentai.images, pages: [] } },
        },
        ...collection.get(),
      ])
    }
  }
</script>

<button class="btn-secondary btn-square btn" on:click={onToggleCollection}>
  {#if isFavorited}
    <MinusIcon class="w-8" />
  {:else}
    <PlusIcon class="w-7" />
  {/if}
</button>
