// apps/web-next/src/modules/main/components/listing.tsx
import React from 'react'

import { Listing } from '../../../core/components/listing'
import { Pagination } from '../../../core/components/pagination'
import { useMainNavigation } from '../services/useMainNavigation'

interface IProps {
  page: number
}

export const MainListing: React.FC<IProps> = props => {
  const { page } = props

  const { data, isLoading, isError } = useMainNavigation(page)
  // const res = useMainNavigation(page)

  return (
    <div className="p-2 sm:p-4">
      {isError ? (
        <div>Fail</div>
      ) : isLoading ? (
        <div>Load</div>
      ) : (
        <React.Fragment>
          <div className="flex justify-center pt-4">
            <nav className="z-0">
              <Pagination max={data.maxPage} current={page} prefix="/" />
            </nav>
          </div>
          <div className="py-4">
            <Listing {...{ galleries: data.galleries }} />
          </div>
          <div className="flex justify-center pb-4">
            <nav className="z-0">
              <Pagination max={data.maxPage} current={page} prefix="/" />
            </nav>
          </div>
        </React.Fragment>
      )}
    </div>
  )
}

// src/modules/listing/components/Listing.svelte
<script lang="ts">
  import { useStore } from '$storeon'
  import Pagination from '$core/components/Pagination.svelte'
  import Poster from '$core/components/Poster.svelte'

  import { getListing } from '../services/getListing'

  import type { SearchStore } from '$storeon/@types/SearchStore'

  export let section: keyof SearchStore['search']
  export let page: number

  const prefix = section === 'main' ? '/' : '/listing/'

  const { search } = useStore('search')
</script>

{#await getListing(page, $search[section], section)}
  <div class="p-32 flex flex-col items-center">
    <progress class="progress w-56" />
    <p class="text-base-content text-sm pt-2">Loading...</p>
  </div>
{:then { items, maxPage }}
  <section class="flex justify-center py-6">
    <Pagination max={maxPage} current={page} {prefix} />
  </section>

  <section class="grid grid-cols-2 gap-8 items-center px-4">
    {#each items as hentai}
      <a href={`/g/${hentai.id}`}>
        <Poster {hentai} />
      </a>
    {/each}
  </section>

  <section class="flex justify-center py-6">
    <Pagination max={maxPage} current={page} {prefix} />
  </section>
{:catch}
  <p>Failed</p>
{/await}
