// apps/web-next/src/pages/collection/import.tsx
import React, { useState } from 'react'

import { NextPage } from 'next'
import Link from 'next/link'

import { CollectionStore, useStoreon } from '@rayriffy-h/state-engine'
import { Check } from '@rayriffy-h/icons'
import { APIResponse } from '@rayriffy-h/helper'

import { Step } from '../../core/components/step'
import { HeadTitle } from '../../core/components/headTitle'

const Page: NextPage = props => {
  const { collection, dispatch } = useStoreon('collection')

  const [input, setInput] = useState<string>('')
  const [error, setError] = useState<Error | null>(null)
  const [status, setStatus] = useState<number>(0)

  const importHandler = async (input: string) => {
    try {
      setError(null)
      setStatus(1)

      const res: APIResponse<CollectionStore['collection']> = await fetch(
        `/api/collection/import/${input}`
      ).then(o => o.json())

      const remoteCollection = res.response.data

      if (remoteCollection.version === collection.version) {
        dispatch('collection/override', {
          collection: {
            ...collection,
            data: remoteCollection.data,
          },
        })

        setStatus(2)
      } else {
        setError(
          new Error(
            'Mismatch version! Please make sure that both of device is running on latest version before exporting.'
          )
        )
      }
    } catch (e) {
      setError(
        new Error(
          'Failed to import data. This might happen because transfer key is not found/expired or failure during import process. Please recheck transfer key, then wait for a few minutes and try again. Sorry... (*_ _)人'
        )
      )
      setStatus(0)
    }
  }

  return (
    <React.Fragment>
      <HeadTitle />
      <div className="max-w-7xl mx-auto px-0 sm:px-4 lg:px-6 pt-6">
        <div className="max-w-3xl mx-auto space-y-6">
          <Step current={status + 1} total={3} />
          <div className="bg-white overflow-hidden shadow sm:rounded-lg">
            <div className="px-4 py-5 sm:p-6">
              <div className="pb-5 border-b border-gray-200 space-y-2">
                <h3 className="text-lg leading-6 font-medium text-gray-900">
                  Import
                </h3>
                <p className="max-w-4xl text-sm leading-5 text-gray-500">
                  {error === null
                    ? 'With this feature, you can import collection from another device by using temporary transfer key. Keep in mind that all of the current collection will be replaced with imported collection.'
                    : error.message}
                </p>
              </div>
              <div className="pt-4">
                {status === 0 ? (
                  <React.Fragment>
                    <div className="pb-4">
                      <label
                        htmlFor="transfer"
                        className="block text-sm font-medium leading-5 text-gray-700"
                      >
                        Transfer key
                      </label>
                      <div className="mt-1 relative rounded-md shadow-sm">
                        <input
                          id="transfer"
                          name="transfer"
                          type="text"
                          className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                          placeholder="Type your key here"
                          aria-describedby="transfer-description"
                          value={input}
                          onChange={({ target: { value } }) => {
                            setInput(value)
                          }}
                        />
                      </div>
                      <p
                        className="mt-2 text-sm text-gray-500"
                        id="transfer-description"
                      >
                        You can obtain transfer key by <b>export</b> it.
                      </p>
                    </div>
                    <div className="">
                      <span className="inline-flex rounded-md shadow-sm mr-4">
                        <Link href="/collection">
                          <a>
                            <button
                              type="button"
                              className="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                            >
                              Back
                            </button>
                          </a>
                        </Link>
                      </span>
                      <span className="inline-flex rounded-md shadow-sm">
                        <button
                          type="button"
                          onClick={() => importHandler(input)}
                          disabled={input === ''}
                          className={`${
                            input === ''
                              ? 'bg-indigo-400 hover:bg-indigo-500 focus:ring-indigo-300'
                              : 'bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500'
                          } inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white focus:outline-none focus:ring-2 focus:ring-offset-2`}
                        >
                          {input === '' ? 'Missing input' : 'Import'}
                        </button>
                      </span>
                    </div>
                  </React.Fragment>
                ) : status === 1 ? (
                  <div className="pt-4 pb-2">
                    <div className="flex justify-center">
                      <div className="w-8 h-8 spinner border-2" />
                    </div>
                    <div className="pt-2">
                      <p className="font-bold text-lg text-gray-800 text-center">
                        In progress...
                      </p>
                      <p className="text-sm text-gray-800 text-center">
                        Importing and processing data from server
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="pt-4 pb-2">
                    <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
                      <Check className="h-6 w-6 text-green-600" />
                    </div>
                    <div className="pt-2">
                      <p className="font-bold text-lg text-gray-800 text-center">
                        Completed!
                      </p>
                      <p className="text-sm text-gray-800 text-center">
                        Data has been transfered to this device
                      </p>
                    </div>
                    <div className="flex justify-center pt-4">
                      <span className="inline-flex rounded-md shadow-sm">
                        <Link href="/collection">
                          <a>
                            <button
                              type="button"
                              className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                            >
                              Back
                            </button>
                          </a>
                        </Link>
                      </span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  )
}

export default Page

// src/routes/collection/import/+page.svelte
<script lang="ts">
  import ErrorIcon from '$icons/errorCircle.svelte'

  import { useStore } from '$storeon'

  import type { APIResponse } from '$core/@types/APIResponse'
  import type { CollectionStore } from '$storeon/@types/CollectionStore'

  let status: 'wait' | 'process' | 'done' = 'wait'
  let error: string | null = null
  let inputKey: string = ''

  const { collection, dispatch } = useStore('collection')

  const onSubmit = async (targetKey: string) => {
    status = 'process'
    error = null

    const response: APIResponse<CollectionStore['collection']> = await fetch(
      `/api/collection/import?${new URLSearchParams({
        code: targetKey,
      }).toString()}`,
      {
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
      }
    ).then(o => o.json())

    if (response.status === 'failed') {
      error =
        'Unable to import collection you specified, maybe code is already expired'
      status = 'wait'
    } else if (response.response.data.version !== $collection.version) {
      error =
        'Mismathed version! Please make sure both device are running the latest version before exporting/importing'
      status = 'wait'
    } else {
      dispatch('collection/override', {
        collection: response.response.data,
      })

      status = 'done'
    }
  }
</script>

<svelte:head>
  <title>Import · Riffy H</title>
</svelte:head>

<section class="p-4">
  <div class="card bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="card-title">Import</h2>
      <p class="text-gray-500">
        Transfer collection from other deivces by using temporary key.
      </p>
      {#if error !== null}
        <div class="alert alert-error my-2 text-sm shadow-lg">
          <div>
            <ErrorIcon class="h-6 w-6 flex-shrink-0" />
            <span>{error}</span>
          </div>
        </div>
      {/if}
      {#if status === 'wait'}
        <input
          type="text"
          placeholder="Temporary key"
          class="input-bordered input w-full font-mono"
          on:input={({ target }) => {
            // @ts-ignore
            inputKey = target?.value ?? ''
          }}
        />
        <div class="card-actions justify-end pt-2">
          <button
            class="btn-primary btn"
            disabled={inputKey === ''}
            on:click={() => onSubmit(inputKey)}
            >{inputKey !== '' ? 'Import' : 'Missing input'}</button
          >
        </div>
      {:else if status === 'process'}
        <div class="flex flex-col items-center pb-2 pt-8">
          <progress class="progress w-56" />
          <p class="pt-2 text-sm text-base-content">Importing...</p>
        </div>
      {:else if status === 'done'}
        <div class="flex flex-col items-center pb-4 pt-6">
          <p class="pt-2 text-base-content">Collection imported! 👍🏼</p>
        </div>
        <div class="card-actions justify-end pt-2">
          <a href="/collection" class="btn-primary btn">Done</a>
        </div>
      {/if}
    </div>
  </div>
</section>
