// web/src/modules/reader/TagsRenderer.svelte
<script lang="ts">
  import { tags as tagTypes } from '$core/constants/tags'
  import { filterTagByType } from '$core/services/filterTagByType'

  import type { DatabaseTag, Tag } from '@riffyh/commons'

  interface Props {
    tags: Tag[]
  }

  let { tags }: Props = $props()

  const sortedTags = tagTypes
    .map(
      type => [type, filterTagByType(tags, type.name)] as [DatabaseTag, Tag[]]
    )
    .filter(([_, o]) => o.length !== 0)
</script>

{#each sortedTags as [type, tags]}
  <div class="flex pt-2">
    <span
      class="pr-2 pt-1 text-sm font-bold uppercase text-gray-700 dark:text-white"
    >
      {type.name}
    </span>
    <div class="flex flex-wrap">
      {#each tags as tag}
        <a
          href={`/tag/${tag.id}`}
          class={`rounded-md px-2 py-1 text-xs uppercase text-white ${type.color} m-1 font-semibold`}
        >
          {tag.name}
        </a>
      {/each}
    </div>
  </div>
{/each}

// client/src/modules/reader/TagsRenderer.tsx
import { TagType, type Tag } from "@riffyh/commons";
import { Fragment, type FunctionComponent } from "react";
import { Link } from "router";
import { tagTypes } from "./tagTypes";

interface Props {
  tags: Tag[];
}

export const TagsRenderer: FunctionComponent<Props> = ({ tags }) => {
  const sortedTags = tagTypes
    .map(
      (type) =>
        [type, tags.filter((tag) => tag.type === type.type)] as [
          { color: string; type: TagType },
          Tag[],
        ],
    )
    .filter(([_, o]) => o.length !== 0);

  return (
    <Fragment>
      {sortedTags.map(([type, tags]) => (
        <div className="flex pt-2" key={`tag-group-${type.type}`}>
          <span className="pr-2 pt-1 text-sm font-bold uppercase text-gray-700 dark:text-white">
            {type.type}
          </span>
          <div className="flex flex-wrap">
            {tags.map((tag) => (
              <Link
                key={`tag-${tag.id}`}
                to="/t/:key/:id"
                params={{ key: tag.key, id: tag.id }}
                className={`rounded-md px-2 py-1 text-xs uppercase text-white ${type.color} m-1 font-semibold`}
              >
                {tag.name}
              </Link>
            ))}
          </div>
        </div>
      ))}
    </Fragment>
  );
};
