// src/core/components/poster.tsx
import { memo } from 'react'

import Link from 'next/link'

import { BookOpenIcon } from '@heroicons/react/24/outline'

import { ImageBlur } from './imageBlur'
import { getImageUrl } from '../services/getImageUrl'
import { tags } from '../constants/tags'

import { MinifiedHentaiForListing } from '../@types/MinifiedHentaiForListing'

interface IProps {
  hentai: MinifiedHentaiForListing
}

const availableFlags = ['english', 'japanese', 'chinese']

export const Poster = memo<IProps>(props => {
  const { hentai } = props

  console.log(hentai)

  return (
    <div className="bg-gray-200 overflow-hidden rounded-xl relative">
      <Link href={`/g/${hentai.id}`} scroll>
        <div className="absolute top-0 bottom-0 left-0 right-0 w-full bg-black-overlay z-10 transition ease-in-out duration-200 opacity-0 hover:opacity-100 text-white flex flex-col justify-between px-4 py-8 md:px-5 lg:px-6 md:py-9 lg:py-10">
          <div>
            <div className="flex">
              {hentai.languages.map(lang =>
                availableFlags.includes(lang.name) ? (
                  <div
                    className="pb-2 pr-2 w-10"
                    key={`poster-${hentai.id}-language-${lang.name}`}
                  >
                    <img
                      src={`/static/img/flags/${lang.name}.png`}
                      alt={lang.name}
                    />
                  </div>
                ) : null
              )}
            </div>
            <p className="font-semibold truncate text-md sm:text-lg md:text-xl">
              {hentai.title}
            </p>
            <div className="pt-2 sm:pt-4 md:pt-6 flex justify-evenly text-center text-xs sm:text-sm md:text-md">
              {tags.map(tag => {
                const { amount } = hentai.tags.find(o => o.name === tag.name)

                if (amount === 0) {
                  return null
                } else {
                  return (
                    <div key={`poster-${hentai.id}-tag-${tag.name}`}>
                      <div
                        className={`w-2.5 h-2.5 sm:w-3 sm:h-3 md:w-4 md:h-4 rounded-full ${tag.color} mx-auto`}
                      />
                      <p className="pt-0.5 md:pt-1">{amount}</p>
                    </div>
                  )
                }
              })}
            </div>
          </div>
          <div className="pt-1 flex">
            <div className="flex items-center pr-2">
              <BookOpenIcon className="w-8 h-8 pr-2" /> {hentai.num_pages ?? 0}
            </div>
          </div>
        </div>
        <ImageBlur
          src={getImageUrl({
            image: hentai.images.cover,
            type: 'cover',
            mediaId: hentai.media_id,
          })}
          alt={hentai.title}
          width={hentai.images.cover.w}
          height={hentai.images.cover.h}
        />
      </Link>
    </div>
  )
})

// src/core/components/Poster.svelte
<script lang="ts">
  import BlurredImage from './BlurredImage.svelte'

  import { getImageUrl } from '../services/getImageUrl'
  import { tags } from '../../core/constants/tags'

  import type { MinifiedHentaiForListing } from '../@types/MinifiedHentaiForListing'

  export let hentai: MinifiedHentaiForListing

  const availableFlags = ['english', 'japanese', 'chinese']
  const filteredTags = tags
    .map(o => ({
      ...o,
      count: hentai.tags.find(j => j.name === o.name)?.amount ?? 0,
    }))
    .filter(o => o.count !== 0)
</script>

<article class="group relative rounded-lg overflow-hidden">
  <div
    class="absolute top-0 bottom-0 left-0 right-0 w-full transition opacity-0 group-hover:opacity-100 text-white flex flex-col justify-between px-4 py-8 bg-black/75 z-10"
  >
    <div>
      <div class="flex items-center pb-2 justify-between">
        {#each hentai.languages.filter( lang => availableFlags.includes(lang.name) ) as language}
          <div class="pr-2 w-10">
            <img src={`/flags/${language.name}.png`} alt={language.name} />
          </div>
        {/each}
        <div class="flex items-center">
          {hentai.num_pages ?? 0}
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6 pl-1"
            fill="currentColor"
            viewBox="0 0 24 24"
            ><path
              d="M6 22h15v-2H6.012C5.55 19.988 5 19.805 5 19s.55-.988 1.012-1H21V4c0-1.103-.897-2-2-2H6c-1.206 0-3 .799-3 3v14c0 2.201 1.794 3 3 3zM5 8V5c0-.805.55-.988 1-1h13v12H5V8z"
            /><path d="M8 6h9v2H8z" /></svg
          >
        </div>
      </div>
      <p class="font-semibold truncate text-md sm:text-lg md:text-xl">
        {hentai.title}
      </p>
      <div
        class="pt-2 sm:pt-4 md:pt-6 flex justify-evenly text-center text-xs sm:text-sm md:text-md"
      >
        {#each filteredTags as filteredTag}
          <div>
            <div
              class={`w-2.5 h-2.5 sm:w-3 sm:h-3 md:w-4 md:h-4 rounded-full ${filteredTag.color} mx-auto`}
            />
            <p class="pt-0.5 md:pt-1">{filteredTag.count}</p>
          </div>
        {/each}
      </div>
    </div>
  </div>
  <BlurredImage
    src={getImageUrl({
      image: hentai.images.cover,
      type: 'cover',
      mediaId: hentai.media_id,
    })}
    alt={hentai.title}
    width={hentai.images.cover.w}
    height={hentai.images.cover.h}
  />
</article>
