// web/src/core/components/Poster.svelte
<script lang="ts">
  import BlurredImage from './BlurredImage.svelte'

  import { getImageUrl } from '@riffyh/commons'

  import type { MinifiedHentaiForListing } from '../@types/MinifiedHentaiForListing'

  interface Props {
    hentai: MinifiedHentaiForListing
  }

  let { hentai }: Props = $props()

  const availableFlags = ['english', 'japanese', 'chinese']
</script>

<article class="group relative">
  <div class="overflow-hidden rounded-xl shadow-md">
    <BlurredImage
      src={getImageUrl({
        image: hentai.images.cover,
        type: 'cover',
        mediaId: hentai.media_id,
      })}
      alt={hentai.title}
      width={hentai.images.cover.w}
      height={hentai.images.cover.h}
    />
  </div>
  <section class="mt-3">
    <div class="flex items-center space-x-2">
      {#each hentai.languages.filter( lang => availableFlags.includes(lang.name) ) as language}
        <img
          src={`/flags/${language.name}.png`}
          alt={language.name}
          class="h-5"
        />
      {/each}
      <p class="truncate font-medium text-base-content">
        {hentai.title}
      </p>
    </div>
  </section>
</article>

// client/src/modules/listings/Poster.tsx
import type { Gallery } from "@riffyh/commons";
import { BlurredImage } from "modules/layout/BlurredImage";
import type { FunctionComponent } from "react";

interface Props {
  gallery: Omit<Gallery, "pages" | "tags">;
}

export const Poster: FunctionComponent<Props> = ({ gallery }) => {
  return (
    <article className="group relative">
      <div className="flex justify-center">
        <div className="overflow-hidden rounded-lg">
          <BlurredImage
            src={gallery.cover.src}
            dataSource={gallery.key}
            alt={gallery.title.display}
            width={gallery.cover.width}
            height={gallery.cover.height}
            type="cover"
          />
        </div>
      </div>
      <section className="mt-3">
        <div className="flex justify-between space-x-2">
          {gallery.language && <img src={"/flags/" + gallery.language + ".svg"} className="w-6" />}
          <p className="truncate font-medium text-base-content">{gallery.title.display}</p>
        </div>
      </section>
    </article>
  );
};
